# Test installing PISM's dependencies using Homebrew and building PISM from sources
name: Dependencies using Homebrew, PISM from sources

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-13, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          brew update
          export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1
          brew install cmake pkg-config fftw gsl netcdf open-mpi petsc udunits
      - run: cmake -B build -S . -DCMAKE_C_FLAGS="-Werror" -DCMAKE_CXX_FLAGS="-Werror"
      - run: make -j -C build all
